source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'puma' #instead of webbrick
gem 'bootstrap-sass'
gem 'simple_form'
gem 'redcarpet' #markdown to html parsing
gem 'devise' #authentication and authorization

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'spring-commands-rspec' #used if using spring and rspec
  gem 'spring-commands-cucumber' #used if using spring and cucumber
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end

group :test do
  gem 'capybara'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'shoulda-matchers', require: false
end

group :development do
  gem 'web-console'
end
